#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${SCRIPT_DIR}/factorio_bridge_config.sh"

export FACTORIO_RCON_HOST="${RCON_HOST}"
export FACTORIO_RCON_PORT="${RCON_PORT}"
export FACTORIO_RCON_PASSWORD="${RCON_PASSWORD}"

export FACTORIO_USER_DATA_DIR="${SERVER_FACTORIO_DIR}"

export FACTORIO_POSITION_COMMAND="${FACTORIO_POSITION_COMMAND}"
export FACTORIO_RAW_POSITION_COMMAND="${FACTORIO_RAW_POSITION_COMMAND}"
export FACTORIO_MOVE_TO_COMMAND="${FACTORIO_MOVE_TO_COMMAND}"

export FACTORIO_WALK_STEP_SECONDS="${FACTORIO_WALK_STEP_SECONDS}"

echo "Factorio bridge environment loaded."
echo "FACTORIO_RCON_HOST=${FACTORIO_RCON_HOST}"
echo "FACTORIO_RCON_PORT=${FACTORIO_RCON_PORT}"
echo "FACTORIO_USER_DATA_DIR=${FACTORIO_USER_DATA_DIR}"